name: hackathon_portugal
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  flutter_modular: ^5.0.3
  cupertino_icons: ^1.0.2
  google_fonts: 6.1.0
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  logger: ^2.0.2+1
  percent_indicator: ^4.2.3
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #    - family: Satoshi
  #      fonts:
  #        - asset: assets/fonts/Satoshi-Variable.ttf
  #        - asset: assets/fonts/Satoshi-VariableItalic.ttf